### PR TITLE
Philips Hue Groups

### PR DESCRIPTION
**Pull request by dainon**
This pull request takes the same concepts that you have in your lights.rb file, but in a class that breaks apart the different light functions. Some features are still in the works, but the groups allow all the lights in a room to act simultaneously with the action. 

I had to use my own nest repository as the main one didn't have the structure_id in the indexes used on my system. I don't know how to resolve that for now, so you might not want to have that in your Gemfile.

I also added instructions for "Getting Started" using the groups. I think your Amazon Echo with Philips Hue work-around is great and I would like to keep adding features if you are interested.

*NOTE: After I did this pull request, I noticed I forgot to uncomment your lights.rb file. I did that as a sanity check on my end that the code wasn't being used during my edits.

### CODE REVIEW

**Comment by zachfeldman** [comment]
Hey @dainon , this is amazing! A few notes:
- You don't have to comment out code, just delete it, history is stored in `git` so we don't have to worry about that
- Your class is really specific to a person's light groups - I wanted this code to be more general and people could modify it themselves. The array of my lights is a relic that I meant to remove from the main codebase. If there is configurability, I'd want it to be separated out into a separate file with examples that people can change if they want to add light groups
- Ruby method names should not be capitalized, they're not constants. You can camelcase them (methodName) but most Ruby programs use underscores (method_name).
- Have you tested this code with an Echo and do you actually own this many lights? Crazy!!

Great work!

**Comment by dainon** [comment]
I agree with you about an easy way to configure it. I'm not a Ruby programmer. I program for a living, but mostly in C#. I'm also a computational linguist by education, so this really excites me. I've written my own Echo's in years past. They don't compare to the speech recognition of megalith companies like Google, Apple and now Amazon, but cool nonetheless. I'll try to conform to the standards preferred.

Yes, I do have all those lights. I'm super into home automation with all the new things they have out these days. I have 25 lights in my house so far. I'm working on other home automation for my home as well and want them all to be controlled by voice.

The thing I found about the groups is that the lights can act in unison. You can have one light in a group and name it whatever. I'm all for having control over certain lights and groups. I just wanted to share with you before getting too far into it.

**Comment by dainon** [comment]
Oh, and yes. I have tested the code on my lights.

**Comment by zachfeldman** [comment]
That's so cool @dainon ! I think with a few minor tweaks your PR will be ready to merge.

The groups is an amazing idea but if we could just cut down that code a bit as basically an example and perhaps also separate it out into a configuration file of some kind. This way, you could .gitignore your version of the file and we could also have a default version for people to configure on their own.

**Comment by dainon** [comment]
I can do some configuration to streamline the setup process. I see you have a new overhauled version. I like that you've split things among their own folders.

**Comment by zachfeldman** [comment]
Thanks! Perhaps you want to re-work you pull request with my suggestions and the new format in mind. Glad to help out further. thanks for your work @dainon .

**Comment by dainon** [comment]
I will do that. I'm new to online collaboration, so let me know if I do something wonky. I'm going to send a new Pull Request after integration into your new format.

**Comment by zachfeldman** [comment]
Looks like @sarkonovich already did Groups in his latest PR!

Also, Amazon is now supporting this natively. crazy!

**Comment by dainon** [comment]
Well, It's been a pleasure playing around with your code base. Since you've mentioned Amazon supports Philips Hue natively, I've been having fun with it in my home. Considering that, I don't have a need to keep at this project. Thanks for all your work and enjoy all projects to come.

**Comment by zachfeldman** [comment]
Hey no worries @dainon , I completely get that. To be fair I probably would've never started this project if native implementation had already been done!

**Comment by dainon** [comment]
Agreed. I just thought it would take them a bit to get around to it. I'm super impressed with the new features they've been rolling out on a regular basis. It's changed my direction on home automation. Now I want everything that will be voice activated.

Last night when I got home from my pool league, mostly by voice I turned on the lights, sat on my couch (not by voice, LOL), asked to have an alarm set for 7AM, set the sleep timer on my TV for 1 hour (not by voice), asked for the weather as we had storms coming, asked to have the lights turned off, fell asleep, woke to the alarm, requested a snooze, turned off the alarm, turned on the lights, requested Toadies radio on Pandora, got ready for work, requested the music to be shut-off and turn the lights off. All without any effort! What a great product! Too many years have gone by without such a device. All the people I talk to that say, "Why do you need that?" should come over and live with it for a day. It's good fun and totally useful!

**Comment by zachfeldman** [comment]
I'm in complete agreement and my days have been like this since I put together the hack =).

**Pull request closed without merging**
